# Generated by Django 2.1.2 on 2018-11-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_profile_picture'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
