# Generated by Django 2.1.2 on 2018-11-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
