# Generated by Django 2.1.3 on 2018-11-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cateogry',
            new_name='category',
        ),
    ]
