# Generated by Django 2.1.2 on 2018-11-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='max_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='max_lon',
        ),
        migrations.RemoveField(
            model_name='place',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='min_lon',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_photo',
        ),
    ]
