# Generated by Django 2.1.2 on 2018-11-05 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
        ('place', '0002_auto_20181105_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='max_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='max_lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='min_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='min_lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='as', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='place_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.Picture'),
        ),
    ]
