# Generated by Django 2.1.2 on 2018-11-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='channel_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
