# Generated by Django 2.1.2 on 2018-11-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('picture_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.Picture')),
            ],
        ),
    ]
